[package]
name = "rparser"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
pest.workspace = true
pest_derive.workspace = true
indexmap.workspace = true
tera.workspace = true
regex.workspace = true
askama.workspace = true