[package]
name = "rlex"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
pest.workspace = true
pest_derive.workspace = true
tera.workspace = true
heck.workspace = true
bitvec.workspace = true
indexmap.workspace = true
clap = { version = "4.5.47", features = ["derive"] }